config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'static_pages#index'

  resources :automobiles
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/automobile.rb
class Automobile < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/automobiles_controller.rb
class AutomobilesController < ApplicationController

  def index 
    @automobiles = Automobile.all
    render :index
  end

  def show
    @automobile = Automobile.find(params[:id])
    @automobile
  end

  def new
    @automobile = Automobile.new
  end


    def create
      @automobile = Automobile.create(automobile_params)
    if @automobile.valid?
      redirect_to action: :index
    else
       render :new, status: :unprocessable_entity
    end

  end

private

  def automobile_params
    params.require(:automobile).permit(:year, :make, :model, :style, :transmission)
  end  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def privacy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/automobiles_helper.rb
module AutomobilesHelper
end

app/views/automobiles/index.html.erb
<h1>Automobiles#index</h1>
  <% @automobiles.each do |auto| %>
    <h2 class="text-center"><%= auto.make %></h2>
  <% end %>

    

app/views/automobiles/new.html.erb
<br />
<div class="booyah-box col-10 offset-1">
  <h1>Add a new automobile</h1>
  <%= simple_form_for @automobile, url: automobile_path do |f| %>
    <%= f.input :make %>
    <%= f.input :model %>
    <%= f.input :year %>
    <%= f.input :style %>
    <%= f.input :transmission %>
    <br />
    <%= f.submit "Create", class: 'btn btn-primary' %>
    <br />
  <% end %>
  <br />
</div>

app/views/automobiles/show.html.erb
<h1>Automobiles#show</h1>
<p>
<b><%= @automobile.model %></b>
</p>
<p>
 <%= @automobile.make %>
</p>
<p>
 <%= @automobile.year %>
</p>
<p>
 <%= @automobile.style %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Auto</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="navbar-text float-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
</p>

    <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
    <%= yield %>
  </body>
</html>

app/views/static_pages/index.html.erb
<h1>Welcome to the Home Page "AUTOCLICK"</h1>